DATASET:
  TEST:
    SOURCE_NAME: "SignAll"
    SOURCE_PATH: "./data/source/sign-all/test"
    TARGET_NAME: "YumiAll"
    TARGET_PATH: "./data/target/yumi-all"
MODEL:
  CHECKPOINT: "./saved/models/checkpoints"
HYPER:
  EPOCHS: 1
  BATCH_SIZE: 1
  LEARNING_RATE: 0.00003
INFERENCE:
  H5:
    BOOL: True
    PATH: "./saved/inferenced/"
