DATASET:
  TEST:
    SOURCE_NAME: "SignAll"
    SOURCE_PATH: "./data/source/sign-all/test"
    TARGET_NAME: "YumiAll"
    TARGET_PATH: "./data/target/yumi-all"
MODEL:
  NAME: "YumiNet"
  CHECKPOINT: "./saved/models/checkpoints"
HYPER:
  EPOCHS: 1
  BATCH_SIZE: 1
  LEARNING_RATE: 0.00003
LOSS:
  EE: True
  VEC: True
  COL: True
  COL_THRESHOLD: 0.15
  LIM: False
  ORI: True
  ORI_LOSS_CALC_METHOD: False
  FIN: True
  REG: True
  LOSS_USING_GAIN: True
  #             ee,    vec,   col,  lim,   ori,   fin,   reg
  LOSS_GAIN: [[2000], [500], [100], [0], [2000], [800], [50]]
INFERENCE:
  H5:
    BOOL: True
    PATH: "./saved/inferenced/"
