MODEL:
  NAME: "YumiNet"
LOSS:
  EE: True
  VEC: True
  COL: True
  COL_THRESHOLD: 0.15
  LIM: False
  ORI: True
  ORI_LOSS_CALC_METHOD: False
  FIN: True
  REG: True
  LOSS_USING_GAIN: True
#               ee,       vec,    col,  lim,  ori,    fin,  reg
  LOSS_GAIN: [[100000], [80000], [100], [0], [6000], [800], [20]]
