hand_cfg = {
    "joints_name": [
        "Link111_shift",
        "Link1",
        "Link11",
        "Link2",
        "Link22",
        "Link3",
        "Link33",
        "Link4",
        "Link44",
        "Link5",
        "Link51",
        "Link52",
        "Link53",
    ],
    "edges": [
        ["Link111_shift", "Link1"],
        ["Link1", "Link11"],
        ["Link111_shift", "Link2"],
        ["Link2", "Link22"],
        ["Link111_shift", "Link3"],
        ["Link3", "Link33"],
        ["Link111_shift", "Link4"],
        ["Link4", "Link44"],
        ["Link111_shift", "Link5"],
        ["Link5", "Link51"],
        ["Link51", "Link52"],
        ["Link52", "Link53"],
    ],
    "root_name": "Link111_shift",
    "end_effectors": ["Link11", "Link22", "Link33", "Link44", "Link53"],
    "elbows": ["Link1", "Link2", "Link3", "Link4", "Link5"],
}
yumi_cfg = {
    "joints_name": [
        "yumi_joint_1_l",
        "yumi_joint_2_l",
        "yumi_joint_7_l",
        "yumi_joint_3_l",
        "yumi_joint_4_l",
        "yumi_joint_5_l",
        "yumi_joint_6_l",
        "yumi_joint_1_r",
        "yumi_joint_2_r",
        "yumi_joint_7_r",
        "yumi_joint_3_r",
        "yumi_joint_4_r",
        "yumi_joint_5_r",
        "yumi_joint_6_r",
    ],
    "edges": [
        ["yumi_joint_1_l", "yumi_joint_2_l"],
        ["yumi_joint_2_l", "yumi_joint_7_l"],
        ["yumi_joint_7_l", "yumi_joint_3_l"],
        ["yumi_joint_3_l", "yumi_joint_4_l"],
        ["yumi_joint_4_l", "yumi_joint_5_l"],
        ["yumi_joint_5_l", "yumi_joint_6_l"],
        ["yumi_joint_1_r", "yumi_joint_2_r"],
        ["yumi_joint_2_r", "yumi_joint_7_r"],
        ["yumi_joint_7_r", "yumi_joint_3_r"],
        ["yumi_joint_3_r", "yumi_joint_4_r"],
        ["yumi_joint_4_r", "yumi_joint_5_r"],
        ["yumi_joint_5_r", "yumi_joint_6_r"],
    ],
    "root_name": ["yumi_joint_1_l", "yumi_joint_1_r"],
    "end_effectors": ["yumi_joint_6_l", "yumi_joint_6_r"],
    "shoulders": ["yumi_joint_2_l", "yumi_joint_2_r"],
    "elbows": ["yumi_joint_4_l", "yumi_joint_4_r"],
}
