HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 35
  BATCH_SIZE: 45
  LEARNING_RATE: 0.000085
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 25
OTHERS:
  SAVE: "./saved/models/yumi_1"
  SUMMARY: "./saved/runs/yumi_1"
MODEL:
  LOAD_CHECKPOINT: False
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
