HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 30
  BATCH_SIZE: 35
  LEARNING_RATE: 0.00005
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 8
OTHERS:
  SAVE: "./saved/models/yumi_3"
  LOG: "./saved/log/yumi_3"
  SUMMARY: "./saved/runs/yumi_3"
MODEL:
  LOAD_CHECKPOINT: True
  CHECKPOINT: "./saved/models/checkpoints/best_model_loss_796.49.pth"
