HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 30
  BATCH_SIZE: 35
  LEARNING_RATE: 0.00008
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 5
OTHERS:
  SAVE: "./saved/models/yumi_1"
  LOG: "./saved/log/yumi_1"
  SUMMARY: "./saved/runs/yumi_1"
MODEL:
  LOAD_CHECKPOINT: True
  CHECKPOINT: "./saved/models/checkpoints/best_model_loss_792.52.pth"
