HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 30
  BATCH_SIZE: 35
  LEARNING_RATE: 2e-9
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 15
OTHERS:
  SAVE: "./saved/models/yumi_3"
  SUMMARY: "./saved/runs/yumi_3"
  LOG: "./saved/log/yumi_3"
MODEL:
  LOAD_CHECKPOINT: TRue
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
