HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 30
  BATCH_SIZE: 35
  LEARNING_RATE: 0.0001
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 30
OTHERS:
  SAVE: "./saved/models/yumi_5"
  LOG: "./saved/log/yumi_5"
  SUMMARY: "./saved/runs/yumi_5"
MODEL:
  LOAD_CHECKPOINT: False
