HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 25
  BATCH_SIZE: 35
  LEARNING_RATE: 5e-10
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 75
OTHERS:
  SAVE: "./saved/models/yumi_4"
  SUMMARY: "./saved/runs/yumi_4"
  LOG: "./saved/log/yumi_4"
MODEL:
  LOAD_CHECKPOINT: TRue
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
