HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 25
  BATCH_SIZE: 35
  LEARNING_RATE: 0.000085
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 11
OTHERS:
  SAVE: "./saved/models/yumi_4"
  LOG: "./saved/log/yumi_4"
  SUMMARY: "./saved/runs/yumi_4"
