HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 25
  BATCH_SIZE: 35
  LEARNING_RATE: 0.000085
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 8
OTHERS:
  SAVE: "./saved/models/yumi_4"
  SUMMARY: "./saved/runs/yumi_4"
MODEL:
  LOAD_CHECKPOINT: True
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
