HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 30
  BATCH_SIZE: 35
  LEARNING_RATE: 0.00008
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 20
OTHERS:
  SAVE: "./saved/models/yumi_2"
  SUMMARY: "./saved/runs/yumi_2"
MODEL:
  LOAD_CHECKPOINT: False
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
