HYPER:
  TRAIN_TIMES: 3
  EPOCHS: 30
  BATCH_SIZE: 35
  LEARNING_RATE: 0.00012
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 10
OTHERS:
  SAVE: "./saved/models/yumi_2"
  LOG: "./saved/log/yumi_2"
  SUMMARY: "./saved/runs/yumi_2"
