HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 65
  BATCH_SIZE: 70
  LEARNING_RATE: 1e-12
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 150
OTHERS:
  SAVE: "./saved/models/yumi_5"
  SUMMARY: "./saved/runs/yumi_5"
  LOG: "./saved/log/yumi_5"
MODEL:
  LOAD_CHECKPOINT: True
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
