HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 30
  BATCH_SIZE: 35
  LEARNING_RATE: 0.000093
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 18
OTHERS:
  SAVE: "./saved/models/yumi_3"
  SUMMARY: "./saved/runs/yumi_3"
MODEL:
  LOAD_CHECKPOINT: False
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
