HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 30
  BATCH_SIZE: 35
  LEARNING_RATE: 0.00001
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 5
OTHERS:
  SAVE: "./saved/models/yumi_1"
  SUMMARY: "./saved/runs/yumi_1"
MODEL:
  LOAD_CHECKPOINT: True
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
