HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 60
  BATCH_SIZE: 120
  LEARNING_RATE: 1e-10
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 20
OTHERS:
  SAVE: "./saved/models/yumi_1"
  SUMMARY: "./saved/runs/yumi_1"
  LOG: "./saved/log/yumi_1"
MODEL:
  LOAD_CHECKPOINT: True
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
