HYPER:
  TRAIN_TIMES: 3
  EPOCHS: 30
  BATCH_SIZE: 20
  LEARNING_RATE: 0.0001
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 10
OTHERS:
  SAVE: "./saved/models/yumi_1"
  LOG: "./saved/log/yumi_1"
  SUMMARY: "./saved/runs/yumi_1"
