HYPER:
  TRAIN_TIMES: 5
  EPOCHS: 65
  BATCH_SIZE: 130
  LEARNING_RATE: 6e-11
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 40
OTHERS:
  SAVE: "./saved/models/yumi_2"
  SUMMARY: "./saved/runs/yumi_2"
  LOG: "./saved/log/yumi_2"
MODEL:
  LOAD_CHECKPOINT: True
  CHECKPOINT: "./saved/models/checkpoints"
  CHECKPOINT_RANDOM: True
