DATASET:
  TRAIN:
    SOURCE_NAME: "SignAll"
    SOURCE_PATH: "./data/source/sign-all/train"
    TARGET_NAME: "YumiAll"
    TARGET_PATH: "./data/target/yumi-all"
  TEST:
    SOURCE_NAME: "SignAll"
    SOURCE_PATH: "./data/source/sign-all/test"
    TARGET_NAME: "YumiAll"
    TARGET_PATH: "./data/target/yumi-all"
MODEL:
  NAME: "YumiNet"
HYPER:
  EPOCHS: 30
  BATCH_SIZE: 35
  LEARNING_RATE: 0.0001
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 10
LOSS:
  EE: True
  VEC: True
  COL: True
  COL_THRESHOLD: 0.15
  LIM: False
  ORI: True
  ORI_LOSS_CALC_METHOD: False
  FIN: True
  REG: True
  LOSS_USING_GAIN: True
#               ee,    vec,   col,  lim,   ori,   fin,   reg
  LOSS_GAIN: [[2000], [200], [100], [0], [2000], [800], [15]]
OTHERS:
  SAVE: "./saved/models/yumi2"
  LOG: "./saved/log/yumi2"
  SUMMARY: "./saved/runs/yumi2"
  LOG_INTERVAL: 39
