DATASET:
  TRAIN:
    SOURCE_NAME: "SignAll"
    SOURCE_PATH: "./data/source/sign-all/train"
    TARGET_NAME: "YumiAll"
    TARGET_PATH: "./data/target/yumi-all"
  TEST:
    SOURCE_NAME: "SignAll"
    SOURCE_PATH: "./data/source/sign-all/test"
    TARGET_NAME: "YumiAll"
    TARGET_PATH: "./data/target/yumi-all"
MODEL:
  NAME: "YumiNet"
HYPER:
  EPOCHS: 20
  BATCH_SIZE: 35
  LEARNING_RATE: 0.00006
  VARIABLE_LEARNING_RATE: True
  VARIABLE_LEARNING_RATE_GAIN: 8
LOSS:
  EE: True
  VEC: True
  COL: True
  COL_THRESHOLD: 0.15
  LIM: False
  ORI: True
  FIN: True
  REG: True
  LOSS_USING_GAIN: True
#              ee, vec, col, lim, ori, fin, reg
  LOSS_GAIN: [[2], [2], [1], [1], [2], [2], [1]]
OTHERS:
  SAVE: "./saved/models/yumi"
  LOG: "./saved/log/yumi"
  SUMMARY: "./saved/runs/yumi"
  LOG_INTERVAL: 38